name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest   # ðŸ‘ˆ IMPORTANT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build Docker frontend image
        run: docker build -t sanjubora84/eadminclient:latest ./client
      - name: Build Docker backend image
        run: docker build -t sanjubora84/eadminbackend:latest ./server
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker frontend image
        run: docker push sanjubora84/eadminclient:latest
      - name: Push Docker Backend image
        run: docker push sanjubora84/eadminbackend:latest
